using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;

public class RandomSceneLanguage : MonoBehaviour
{
    [SerializeField] Text ok;
    [SerializeField] Text get;
    [SerializeField] Text catAllOk;
    [SerializeField] Text catAllText;

    private void Update()
    {
        if (GameControl.control.Language == false)
        {
            ok.text = "확인";
            get.text = "획득"!;
            catAllOk.text = "확인";
            catAllText.text = "모든 고양이 스킨을 다 얻었어요! 야호!";
        }
        else
        {
            ok.text = "Ok";
            get.text = "Get!";
            catAllOk.text = "Ok";
            catAllText.text = "You got\nall cat skins!\nYeah!";
        }
    }
}
